# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm@10.12.1

# Copy configuration files
COPY package.json pnpm-lock.yaml tsconfig.json smithery.config.js ./

# Install dependencies (including dev for build)
RUN pnpm install --frozen-lockfile

# Copy source code
COPY src ./src

# Build artifacts
RUN pnpm run build

# Runtime stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built files and dependencies
COPY --from=builder /app/.smithery ./.smithery
COPY --from=builder /app/node_modules ./node_modules

ENTRYPOINT ["node", ".smithery/index.cjs"]
